replicaCount: 1

image:
  repository: yarencheng/v2ray
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  vmess:
    type: ClusterIP
    port: 80
  socks:
    type: ClusterIP
    port: 1080
  http:
    type: ClusterIP
    port: 8080
  shadowsocks:
    type: ClusterIP
    port: 10086

ingress:
  enabled: false
  annotations: {}
    # cert-manager.io/cluster-issuer: "letsencrypt"
    # kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: v2ray.local
      paths:
        - /
  tls:
   - secretName: v2ray-tls
     hosts:
       - v2ray.local

livenessProbe:
  failureThreshold: 10
  initialDelaySeconds: 0
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10
readinessProbe:
  failureThreshold: 1
  initialDelaySeconds: 0
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

logLevel: debug
inbound:
  vmess:
    enabled: true
    port: 80
    clients:
      - id: 11111111-1111-1111-1111-111111111111
      # - id: 22222222-2222-2222-2222-222222222222
      #   alterId: 1
    streamSetting:
      network: ws # "tcp" | "kcp" | "ws" | "http" | "domainsocket" | "quic"
      wsSettings:
        path: "/"
        headers: []
  socks:
    enabled: false
    port: 1080
    auth: noauth ## "noauth" | "password"
    udp: true
    accounts:
      - user: my-username
        pass: my-password
  http:
    enabled: false
    port: 8080
    timeout: 0
    accounts: []
      # user: my-username
      # pass: my-password
  shadowsocks:
    enabled: false
    port: 10086
    ## "aes-256-cfb" | "aes-128-cfb" | "chacha20" |
    ## "chacha20-ietf" | "aes-256-gcm" | "aes-128-gcm" |
    ## "chacha20-poly1305" | "chacha20-ietf-poly1305"
    method: aes-128-cfb
    password: my-password
    ota: false
    network: tcp ## "tcp" | "udp" | "tcp,udp"

costumeConfig: {}
  # log:
  #   loglevel: debug
  # dns: {}
  # stats: {}
  # inbounds:
  # - port: 80
  #   protocol: vmess
  #   settings:
  #     clients:
  #     - id: 12345678-1234-1234-1234-123456789012
  #       alterId: 32
  #   streamSettings:
  #     network: ws
  #     security: none
  #     wsSettings:
  #       path: "/"
  # outbounds:
  # - protocol: freedom
  #   settings:
  #     domainStrategy: UseIP
  # policy: {}
  # reverse: {}
  # transport: {}