{{- define "stream.settings" -}}
streamSettings:
  network: {{ .network }}
  {{- if eq .network "ws" }}
  {{- with .wsSettings }}
  wsSettings:
    path: {{ .path }}
    {{- if .headers }}
    headers:
      {{- range .headers }}
      - {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- else }}
    {{ printf "unsupported `network=%s`" .network | fail }}
  {{- end }}
  security: none
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "v2ray.fullname" . }}
  labels:
    {{- include "v2ray.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- if .Values.costumeConfig }}
    {{- toYaml .Values.costumeConfig | nindent 4 }}
    {{- else }}
    log:
      loglevel: {{ .Values.logLevel }}
    dns: {}
    stats: {}
    inbounds:
      {{- if .Values.inbound.vmess.enabled }}
      {{- with .Values.inbound.vmess }}
      - port: {{ .port }}
        protocol: vmess
        settings:
          {{- if .clients }}
          clients:
            {{- range .clients }}
            - id: {{ .id }}
              {{- if .alterId }}
              alterId: {{ .alterId }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- include "stream.settings" .streamSetting | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.inbound.socks.enabled }}
      {{- with .Values.inbound.socks }}
      - port: {{ .port }}
        protocol: socks
        settings:
          auth: {{ .auth }}
          udp: {{ .udp }}
          {{- if .accounts }}
          accounts:
            {{- range .accounts }}
            - user: {{ .user }}
              pass: {{ .pass }}
            {{- end }}
          {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.inbound.http.enabled }}
      {{- with .Values.inbound.http }}
      - port: {{ .port }}
        protocol: http
        settings:
          {{- if .accounts }}
          accounts:
            {{- range .accounts }}
            - user: {{ .user }}
              pass: {{ .pass }}
            {{- end }}
          {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.inbound.shadowsocks.enabled }}
      {{- with .Values.inbound.shadowsocks }}
      - port: {{ .port }}
        protocol: shadowsocks
        settings:
          method: {{ .method }}
          password: {{ .password }}
          ota: {{ .ota }}
          network: {{ .network }}
      {{- end }}
      {{- end }}
    outbounds:
      - protocol: freedom
        settings:
          domainStrategy: UseIP
    policy: {}
    reverse: {}
    transport: {}
    {{- end }}