apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "v2ray.fullname" . }}
  labels:
    {{- include "v2ray.labels" . | nindent 4 }}
data:
  config.json: |-
    {{ toJson .Values.config | indent 4 }}