apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "v2ray.fullname" . }}
  labels:
    {{- include "v2ray.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "v2ray.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ toJson .Values | sha256sum }}
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "v2ray.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: transform-to-json-config
          image: mikefarah/yq
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |-
              set -ue
              yq r --tojson /tmp/yaml/config.yaml > /tmp/json/config.json
          resources:
            limits:
              cpu: 100m
              memory: 32Mi
            requests:
              cpu: 100m
              memory: 32Mi
          volumeMounts:
            - name: yaml-config-volume
              mountPath: /tmp/yaml/
            - name: json-config-volume
              mountPath: /tmp/json/
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: vmess
              containerPort: {{ .Values.inbound.vmess.port }}
              protocol: TCP
            - name: socks-tcp
              containerPort: {{ .Values.inbound.socks.port }}
              protocol: TCP
            - name: socks-udp
              containerPort: {{ .Values.inbound.socks.port }}
              protocol: UDP
            - name: http
              containerPort: {{ .Values.inbound.http.port }}
              protocol: TCP
            - name: shadowsocks-tcp
              containerPort: {{ .Values.inbound.shadowsocks.port }}
              protocol: TCP
            - name: shadowsocks-udp
              containerPort: {{ .Values.inbound.shadowsocks.port }}
              protocol: UDP
          # livenessProbe:
          #   tcpSocket:
          #     port: 80
          #   failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          #   periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          #   successThreshold: {{ .Values.livenessProbe.successThreshold }}
          #   initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          #   timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          # readinessProbe:
          #   tcpSocket:
          #     port: 80
          #   failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          #   periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          #   successThreshold: {{ .Values.readinessProbe.successThreshold }}
          #   initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          #   timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: json-config-volume
              mountPath: /etc/v2ray/
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: yaml-config-volume
          configMap:
            name: {{ include "v2ray.fullname" . }}
            items:
              - key: config.yaml
                path: config.yaml
        - name: json-config-volume
          emptyDir: {}
